### ISSUE TITLE
Why not use the torrent lib instead of the torrent CLI tool ?

### ISSUE THREAD

**Issue by karuppiah7890** [BruceWangNo1/remote-torrent#2]
I think the former is more easier to integrate with than using the CLI tool, and scraping data out of the console output

**Comment by BruceWangNo1** [comment]
You have a very good point. But you see, I considered this when I started and I decided to limit the work load. Maybe you can work on it.

**Comment by karuppiah7890** [comment]
@BruceWangNo1 👍I have to first meddle with torrent lib, then I will do it may be 😄

**Comment by BruceWangNo1** [comment]
@karuppiah7890 Good luck to you then.

**Comment by BruceWangNo1** [comment]
For future reference, remote-torrent uses the torrent library instead of its CLI tool in a later commit seen above.
